# Generated by Django 4.2.9 on 2025-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=' ', upload_to='projects/'),
            preserve_default=False,
        ),
    ]
